//------------------------------------------------------------------------------
// <auto-generated>
//     Esse código foi gerado por uma ferramenta.
//
//     As alterações feitas nesse arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for regenerado. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Contas
{


    public partial class RegisterExternalLogin
    {


        /// <summary>
        /// Controle de providerMessage.
        /// </summary>
        /// <remarks>
        /// Campo gerado automaticamente.
        /// Para modificar, mova a declaração de campo do arquivo do designer para o arquivo code-behind.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label providerMessage;


        /// <summary>
        /// Controle de userNameForm.
        /// </summary>
        /// <remarks>
        /// Campo gerado automaticamente.
        /// Para modificar, mova a declaração de campo do arquivo do designer para o arquivo code-behind.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder userNameForm;

        /// <summary>
        /// Controle userName.
        /// </summary>
        /// <remarks>
        /// Campo gerado automaticamente.
        /// Para modificar, mova a declaração de campo do arquivo do designer para o arquivo code-behind.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox userName;


        /// <summary>
        /// Controle de userNameMessage.
        /// </summary>
        /// <remarks>
        /// Campo gerado automaticamente.
        /// Para modificar, mova a declaração de campo do arquivo do designer para o arquivo code-behind.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label userNameMessage;

    }
}
